include("config.jl")
include("misc.jl")
include("utils.jl")
include("reso.jl")
include("newcore.jl")
include("coreprint.jl")
include("dvcreso.jl")
include("analyzer.jl")
include("repl.jl")
include("merge.jl")

println("... cheaplogic is loaded")
