# load all with naive unify
include("config.jl")
include("misc.jl")
include("utils.jl")
include("types.jl")
include("primitives.jl")
include("subst.jl")
include("unifybase.jl")
include("naiveunify.jl")
include("reso.jl")
include("merge.jl")
include("newcore.jl")
include("coreprint.jl")
include("dvcreso.jl")
include("analyzer.jl")
include("repl.jl")
include("parser.jl")

println("... naivelogic is loaded")
