;; all play prover gtail

(load "play-prover-gt-mer001.lisp")
(load "play-prover-gt-ml002.lisp")
(load "play-prover-gt-presem.lisp")
(load "play-prover-gt-sem001.lisp")
(load "play-prover-gt-sem002.lisp")
(load "play-prover-gt-sem003.lisp")
(load "play-prover-gt-sems01.lisp")
(load "play-prover-gt0.lisp")
(load "play-prover-gt000.lisp")
(load "play-prover-gt001.lisp")
(load "play-prover-gt002.lisp")
(load "play-prover-gt003.lisp")
(load "play-prover-gt004.lisp")
(load "play-prover-gt1.lisp")
(load "play-prover-gt2.lisp")
(load "play-prover-gt3.lisp")
(load "play-prover-gt4.lisp")
(load "play-prover-gt5.lisp")
(load "play-prover-gt6loop.lisp")
(load "play-prover-gt7loop.lisp")
(load "play-prover-gt8loop.lisp")
(load "play-prover-gtvv01.lisp")
(load "play-prover-gtvv02.lisp")
